import type { Metadata } from "next";
import "./globals.css";
// import { WalletProvider } from './WalletProvider'; // No longer directly needed here
// import Header from '@/components/header'; // Header is now in RootLayoutClient
import { pressStart2P } from './fonts';
import RootLayoutClient from "@/components/RootLayoutClient"; // Import RootLayoutClient

export const metadata: Metadata = {
  title: "Arcade Time",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pressStart2P.variable}`}>
      <body className="arcade-pixel-font antialiased bg-black min-h-screen">
        <RootLayoutClient>{children}</RootLayoutClient> {/* Use RootLayoutClient here */}
      </body>
    </html>
  );
}
