import type { Metadata } from "next";
import "./globals.css";
import { WalletProvider } from './WalletProvider';
import Header from '@/components/header';

export const metadata: Metadata = {
  title: "Arcade Time",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="arcade-pixel-font antialiased bg-black min-h-screen">
        <WalletProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1">
              {children}
            </main>
          </div>
        </WalletProvider>
      </body>
    </html>
  );
}
